### ISSUE TITLE
All issur

### ISSUE THREAD

**Issue by Eric-qiu1** [npm/documentation#984]
Help for al issue recovery 
```[tasklist]
### Tasks
- [ ] https://github.com/npm/documentation/pull/983
- [ ] https://github.com/npm/documentation/pull/980
- [ ] https://github.com/npm/documentation/pull/966
- [ ] https://github.com/npm/documentation/pull/977
- [ ] https://github.com/npm/documentation/issues/982
- [ ] https://github.com/npm/documentation/pull/974
- [ ] https://github.com/npm/documentation/pull/973
- [ ] https://github.com/npm/documentation/pull/979
- [ ] https://github.com/npm/documentation/issues/978
- [ ] https://github.com/npm/documentation/issues/976
- [ ] https://github.com/npm/documentation/pull/971
- [ ] https://github.com/npm/documentation/pull/972
- [ ] https://github.com/npm/documentation/issues/975
- [ ] https://github.com/npm/documentation/issues/969
- [ ] https://github.com/npm/documentation/pull/970
- [ ] https://github.com/npm/documentation/issues/136
- [ ] https://github.com/npm/documentation/issues/759
- [ ] https://github.com/npm/documentation/pull/968
- [ ] https://github.com/npm/documentation/pull/965
- [ ] https://github.com/npm/documentation/pull/964
- [ ] https://github.com/npm/documentation/pull/963
- [ ] https://github.com/npm/documentation/pull/956
- [ ] https://github.com/npm/documentation/pull/954
- [ ] https://github.com/npm/documentation/pull/949
- [ ] https://github.com/npm/documentation/pull/945
- [ ] https://github.com/npm/documentation/pull/947
- [ ] https://github.com/npm/documentation/pull/960
- [ ] https://github.com/npm/documentation/pull/962
- [ ] https://github.com/npm/documentation/pull/959
- [ ] https://github.com/npm/documentation/pull/957
- [ ] https://github.com/npm/documentation/issues/958
- [ ] https://github.com/npm/documentation/pull/946
- [ ] https://github.com/npm/documentation/pull/948
- [ ] https://github.com/npm/documentation/issues/967
- [ ] https://github.com/npm/documentation/pull/846
- [ ] https://github.com/npm/documentation/pull/952
- [ ] https://github.com/npm/documentation/pull/936
- [ ] https://github.com/npm/documentation/pull/921
- [ ] https://github.com/npm/documentation/pull/953
- [ ] https://github.com/npm/documentation/pull/937
- [ ] https://github.com/npm/documentation/pull/940
- [ ] https://github.com/npm/documentation/pull/938
- [ ] https://github.com/npm/documentation/issues/810
- [ ] https://github.com/npm/documentation/pull/941
- [ ] https://github.com/npm/documentation/pull/943
- [ ] https://github.com/npm/documentation/pull/942
- [ ] https://github.com/npm/documentation/issues/935
- [ ] https://github.com/npm/documentation/pull/939
- [ ] https://github.com/npm/documentation/pull/934
- [ ] https://github.com/npm/documentation/pull/929
- [ ] https://github.com/npm/documentation/pull/928
- [ ] https://github.com/npm/documentation/pull/930
- [ ] https://github.com/npm/documentation/pull/932
- [ ] https://github.com/npm/documentation/pull/920
- [ ] https://github.com/npm/documentation/pull/926
- [ ] https://github.com/npm/documentation/pull/924
- [ ] https://github.com/npm/documentation/pull/927
- [ ] https://github.com/npm/documentation/pull/919
- [ ] https://github.com/npm/documentation/pull/793
- [ ] https://github.com/npm/documentation/pull/931
```
