### ISSUE TITLE
Help restore 

### ISSUE THREAD

**Issue by Eric-qiu1** [npm/documentation#985]
Help
```[tasklist]
### Tasks
- [ ] https://github.com/npm/documentation/pull/966
- [ ] https://github.com/npm/documentation/pull/980
- [ ] https://github.com/npm/documentation/pull/979
- [ ] https://github.com/npm/documentation/issues/982
- [ ] https://github.com/npm/documentation/issues/984
- [ ] https://github.com/npm/documentation/pull/983
- [ ] https://github.com/npm/documentation/pull/974
- [ ] https://github.com/npm/documentation/pull/973
- [ ] https://github.com/npm/documentation/issues/978
- [ ] https://github.com/npm/documentation/issues/976
- [ ] https://github.com/npm/documentation/issues/969
- [ ] https://github.com/npm/documentation/pull/970
```
